# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 49f5633d4a0f954d82f5b7e6c680c9d3937b00e872eb5bfd1fcf8bcc20b5220989e026242cd40d57110b264e3224ed1fbb951b75b763da430f62b4f5b57a6507

test:
  secret_key_base: 1bce743e9c7adbcb867605ef742416202c297b5bf12011133d650aacea875007977225da2fa1b91b3164f297eb58d057dff1aba31a4d21766c64cefbae5814c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
